const ICON_SCALE = 24;

export const GLOBALS = {
  ANDROID_ELEVATION: 4,
  APP_VERSION: '1',
  ICON_SCALE,
  ICON_SIZE: {
    width: ICON_SCALE,
    height: ICON_SCALE,
  },
  ACTIVE_OPACITY: 0.7,
  OTP_TIMEOUT: 60,
  PIN_LENGTH: 4,
  OTP_LENGTH: 6,
  SCREEN_PADDING: 16,
  INSTITUTION_CD: '063',
  USE_MOCK_REQUESTS: false,
  MOCK_REQUESTS_DELAY_MS: 500,
  LOGIN_COUNT_FOR_USERNAME_SAVE: 5,
  OPEN_BANKING: false,
};
