export const REQUESTS = {
  POLLING_INTERVAL_MS: 30000,
  SESSION_TIMEOUT_MESSAGE: 'Authentication Failure',
  STABLE_DATA_REFETCH_TIME: 3600,
  WITHOUT_LOADER: 'HIDE_LOADER',
  MANUAL_ERROR_HANDLE: 'MANUAL_ERROR_HANDLE',
};
